### ISSUE TITLE
Can we create one certificate manually on Cloudflare dashboard and this role picks that instead of creating new certificates every time?

### ISSUE THREAD

**Issue by amankapoor** [TypistTech/trellis-cloudflare-origin-ca#39]
Hi,

I have started using Trellis recently and in the last couple of days, I see that my Cloudflare dashboard has about 4 origin certificates with the same domains in it. 

Is it not possible that we create one origin certificate defining example.com and *.example.com from the dashboard and this plugin picks that instead of creating a new one every time?

I am not very clear about what exactly triggered the new certificates, it might be the creation of a new machine on Google Cloud. I have provisioned the server multiple times so higher chances are that creation of a new machine and then the first provision on that creates a new origin certificate.

Nonetheless, could you please shed some light on this matter. Does Cloudflare limit the number of origin certificates creation? And if by any chance referencing an old manually created certificate is possible, and if that would help.

All I see is 4 certificates on my dashboard which I will manually delete.

**Comment by TangRufus** [comment]
This role makes 1 origin certificate per site on each web server. Generating origin certificate is fast and free, I don't think reusing them on multiple sites adds any benefits.

This example generates 1 origin certificate (on each web server) for all 4 domains.
```yaml
wordpress_sites:
  example.com:
    site_hosts:
      - canonical: example.com
        redirects:
          - ww1.example.com
          - ww2.example.com
          - ww3.example.com
    cloudflare_origin_ca:
      hostnames:
        - example.com
        - '*.example.com'
```

This example generates 2 origin certificates (on each web server), 1 for each site.
```yaml
wordpress_sites:
  example.com:
    site_hosts:
      - canonical: example.com
        redirects:
          - ww1.example.com
          - ww2.example.com
          - ww3.example.com
    cloudflare_origin_ca:
      hostnames:
        - example.com
        - '*.example.com'


  xxx.example.com:
    site_hosts:
      - canonical: xxx.example.com
        redirects:
          - xx1.example.com
          - xx2.example.com
          - xx3.example.com
    cloudflare_origin_ca:
      hostnames:
        - '*.example.com'
```

---

> Is it not possible that we create one origin certificate defining example.com and *.example.com from the dashboard and this plugin picks that instead of creating a new one every time?

Not possible and not intended to.
If you must, use https://roots.io/trellis/docs/ssl/#manual

> what exactly triggered the new certificates

During provision, if `{{ nginx_ssl_path }}/cloudflare-origin-ca/{{ item.key }}.XXX` is absent, this role generates new certificates.

> Does Cloudflare limit the number of origin certificates creation? 

Ask Cloudflare support. I haven't bump into any limiation.

> And if by any chance referencing an old manually created certificate is possible, and if that would help.

If you must, use https://roots.io/trellis/docs/ssl/#manual

---

Learn more on https://discourse.roots.io/t/site-on-trellis-provisioned-do-droplet-subdom-site-on-2nd-droplet-cloudflare-oc/14516/6
