### ISSUE TITLE
Manual + Cloudflare on one server

### ISSUE THREAD

**Issue by eriteric** [TypistTech/trellis-cloudflare-origin-ca#57]
I have multiple sites on one trellis, and some use different cloudflare accounts. When attempting to use a combination of manual and cloudflare it says that it can't find the domain (predictably) but, it shouldn't be trying to because i have those set to manual SSL.
What I've done for now is set all sites to manual, then it provisions successfully.

Another solution could be using multiple account keys and setting them for each site in wordpress_sites.yml or vault.yml
This could just be some weird edge case that nobody ever does though. :)

**Comment by tangrufus** [comment]
Good catch!

We should add support "per site Cloudflare API key" support.

Something like:

```yaml
# In vault.yml

vault_cloudflare_origin_ca_key: v1.0-xxxxxxxxxxx
vault_cloudflare_origin_ca_key_of_another_account: v1.0-yyyyyyyyyyyy

# In wordpress_sites.yml

wordpress_sites:
  example.com:
    cloudflare_origin_ca:
       # No `origin_ca_key` config. Fallback to `vault_cloudflare_origin_ca_key`
  example-another-account.com:
    cloudflare_origin_ca:
       # Plain text string is okay. But, you really want to encrypt it in vault.yml
       origin_ca_key: "{{ vault_cloudflare_origin_ca_key_of_another_account }}"
```

Would you be able to submit a PR?
